return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		local config = require("nvim-treesitter.configs")
		config.setup({
			ensure_installed = {
				"c",
				"lua",
				"vim",
				"vimdoc",
				"query",
				"javascript",
				"typescript",
				"html",
				"css",
				"php",
				"angular",
				"bash",
				"c_sharp",
				"cpp",
				"csv",
				"dockerfile",
				"java",
				"json",
				"pug",
				"python",
				"regex",
				"scss",
				"sql",
				"tsx",
				"vue",
				"xml",
			},
			auto_install = true,
			highlight = { enable = true },
			indent = { enable = true },
		})
	end,
}
